name: Node.js CI/CD

on:
  push:
    branches:
      - main # Trigger on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up SSH for Deployment
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Step 3: Deploy Code and Run build.sh on Server
    - name: Deploy and Build on Server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
        cd /var/www/8-b-master
        git pull origin main
        chmod +x build.sh # Ensure build.sh is executable
        ./build.sh        # Run the build.sh script
        EOF
